const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  onNewFile: cb => ipcRenderer.on('r-new-file', cb),
  onOpenFile: cb => ipcRenderer.on('r-open-file', cb),
  onSaveFile: cb => ipcRenderer.on('r-save-file', cb),
  onSaveAs: cb => ipcRenderer.on('r-save-as', cb),
  onFileOpened: cb => ipcRenderer.on('r-file-opened', cb),
  onAddSlide: cb => ipcRenderer.on('r-add-slide', cb),
  onAddNotes: cb => ipcRenderer.on('r-add-notes', cb),
  onDeleteSlide: cb => ipcRenderer.on('r-delete-slide', cb),
  onSetSlideLayout: cb => ipcRenderer.on('r-set-slide-layout', cb),
  onSetDefaultTransition: cb => ipcRenderer.on('r-set-default-transition', cb),
  onSetSlideTransition: cb => ipcRenderer.on('r-set-slide-transition', cb),
  onSetClear: cb => ipcRenderer.on('r-set-clear', cb),
  onSetTextfit: cb => ipcRenderer.on('r-set-textfit', cb),
  onToggleView: cb => ipcRenderer.on('r-toggle-view', cb),
  onEditCustomCss: cb => ipcRenderer.on('r-edit-custom-css', cb),
  onPlaySlides: cb => ipcRenderer.on('r-play-slides', cb),
  onChangeStylesheet: cb => ipcRenderer.on('r-change-stylesheet', cb),
  onUndo: cb => ipcRenderer.on('r-undo', cb),
  onRedo: cb => ipcRenderer.on('r-redo', cb),
  onSelectAll: cb => ipcRenderer.on('r-select-all', cb),
  onFormatInline: cb => ipcRenderer.on('r-format-inline', cb),
  onFormatLink: cb => ipcRenderer.on('r-format-link', cb),
  onFormatRemoveFormat: cb => ipcRenderer.on('r-format-removeformat', cb),
  onAddImage: cb => ipcRenderer.on('r-add-image', cb),
  onEditClass: cb => ipcRenderer.on('r-edit-class', cb),
  onFormatBlock: cb => ipcRenderer.on('r-format-block', cb),
  onFormatUl: cb => ipcRenderer.on('r-format-ul', cb),
  onFormatOl: cb => ipcRenderer.on('r-format-ol', cb),
  onIncreaseListLevel: cb => ipcRenderer.on('r-increase-list-level', cb),
  onDecreaseListLevel: cb => ipcRenderer.on('r-decrease-list-level', cb),
  onMakeTable: cb => ipcRenderer.on('r-make-table', cb),
  onAddHeaderRow: cb => ipcRenderer.on('r-add-header-row', cb),
  onAddRow: cb => ipcRenderer.on('r-add-row', cb),
  onAddColumn: cb => ipcRenderer.on('r-add-column', cb),
  onDeleteRows: cb => ipcRenderer.on('r-delete-rows', cb),
  onDeleteColumns: cb => ipcRenderer.on('r-delete-columns', cb),
  onToggleHeaderCell: cb => ipcRenderer.on('r-toggle-header-cell', cb),
  onCheckUnsavedChanges: cb => ipcRenderer.on('r-check-unsaved-changes', cb),
  onZoomIn: cb => ipcRenderer.on('r-zoom-in', cb),
  onZoomOut: cb => ipcRenderer.on('r-zoom-out', cb),
  onZoomReset: cb => ipcRenderer.on('r-zoom-reset', cb),
  onStyleHelp: cb => ipcRenderer.on('r-style-help', cb),

  proceedWithClose: () => ipcRenderer.send('a-proceed-with-close'),
  cancelClose: () => ipcRenderer.send('a-cancel-close'),
  saveFileDialog: (currentPath) => ipcRenderer.invoke('a-save-file-dialog',
    currentPath),
  readFile: (filePath) => ipcRenderer.invoke('a-read-file', filePath),
  writeFile: (filePath, content, auth) => ipcRenderer.invoke('a-write-file',
    filePath, content, auth),
  openFile: () => ipcRenderer.invoke('a-open-file'),
  selectCssFile: () => ipcRenderer.invoke('a-select-css-file'),
  selectImageFile: () => ipcRenderer.invoke('a-select-image-file'),
  makeAbsolute: (urlRef, base) => ipcRenderer.invoke('a-make-absolute',
    urlRef, base),
  resolvePath: (...paths) => ipcRenderer.invoke('a-resolve-path', ...paths),
  makeRelativePath: (fromPath, toPath) => ipcRenderer.invoke(
    'a-make-relative-path', fromPath, toPath),
  getTempFilePath: () => ipcRenderer.invoke('a-get-temp-file-path'),
  writeTempFile: (content) => ipcRenderer.invoke('a-write-temp-file', content),
  getRealPath: (path) => ipcRenderer.invoke('a-get-real-path', path),
  updateLayoutAndTransitionsMenus: (json) => ipcRenderer.invoke(
    'a-update-layout-and-transitions-menus', json),
  openInBrowser: (filePath) => ipcRenderer.invoke('a-open-in-browser',
    filePath),
  setClear: (value) => ipcRenderer.send('a-set-clear', value),
  setTextfit: (value) => ipcRenderer.send('a-set-textfit', value),
  showHideClear: (show) => ipcRenderer.send('a-show-hide-clear', show),
  showUndoRedo: (canUndo, canRedo) => ipcRenderer.send('a-show-undo-redo',
    canUndo, canRedo),
  setTitle: (title) => ipcRenderer.send('a-set-title', title),
  getMediaType: (path) => ipcRenderer.invoke('a-get-media-type', path)
});
